spring.application.name=fixcampus
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/fixcampus}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET:fixcampus-clave-local-para-pruebas-2026-esta-clave-debe-tener-al-menos-sesenta-y-cuatro-caracteres-para-hs512}
server.port=${PORT:8080}
app.frontend-url=${FRONTEND_URL:http://localhost:4200}
